# This notebook documents the URLs and sample code to access the COVID-19 data published by Definitive Health Care and how it can be loaded into Azure Synapse or Azure SQL DB

URL of the curated data

CSV: https://covidtrackingdefinitive.blob.core.windows.net/public/curated/covid-19/covid_tracking/latest/covid_tracking.csv?sv=2019-12-12&amp;ss=bfqt&amp;srt=sco&amp;sp=rwdlacupx&amp;se=2025-07-27T20:27:49Z&amp;st=2020-07-27T12:27:49Z&amp;spr=https&amp;sig=%2ForvhRm%2BPnVJRLiocMHayJxTDozY1iCEwtBMtCEI60w%3D

JSON: https://covidtrackingdefinitive.blob.core.windows.net/public/curated/covid-19/covid_tracking/latest/covid_tracking.json?sv=2019-12-12&amp;ss=bfqt&amp;srt=sco&amp;sp=rwdlacupx&amp;se=2025-07-27T20:27:49Z&amp;st=2020-07-27T12:27:49Z&amp;spr=https&amp;sig=%2ForvhRm%2BPnVJRLiocMHayJxTDozY1iCEwtBMtCEI60w%3D

PARQUET: https://covidtrackingdefinitive.blob.core.windows.net/public/curated/covid-19/covid_tracking/latest/covid_tracking.parquet?sv=2019-12-12&amp;ss=bfqt&amp;srt=sco&amp;sp=rwdlacupx&amp;se=2025-07-27T20:27:49Z&amp;st=2020-07-27T12:27:49Z&amp;spr=https&amp;sig=%2ForvhRm%2BPnVJRLiocMHayJxTDozY1iCEwtBMtCEI60w%3D

JSONL: https://covidtrackingdefinitive.blob.core.windows.net/public/curated/covid-19/covid_tracking/latest/covid_tracking.jsonl?sv=2019-12-12&amp;ss=bfqt&amp;srt=sco&amp;sp=rwdlacupx&amp;se=2025-07-27T20:27:49Z&amp;st=2020-07-27T12:27:49Z&amp;spr=https&amp;sig=%2ForvhRm%2BPnVJRLiocMHayJxTDozY1iCEwtBMtCEI60w%3D

Download the dataset file using the built-in capability download from a http URL in Pandas. Pandas has readers for various file formats:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html (use lines=True for json lines)

##### Lets Load data from a CSV file into a data frame

In [41]:
import pandas as pd
import numpy as np

COVID_DEFINITIVE_HC_CSV_URL="https://covidtrackingdefinitive.blob.core.windows.net/public/curated/covid-19/covid_tracking/latest/covid_tracking.csv?sv=2019-12-12&ss=bfqt&srt=sco&sp=rwdlacupx&se=2025-07-27T20:27:49Z&st=2020-07-27T12:27:49Z&spr=https&sig=%2ForvhRm%2BPnVJRLiocMHayJxTDozY1iCEwtBMtCEI60w%3D"

dataFrame = pd.read_csv(COVID_DEFINITIVE_HC_CSV_URL, header=0)

Lets see the column name and their types

In [42]:
dataFrame.dtypes

Row_ID                               int64
Load_Date                           object
Load_Time                           object
Longitude                          float64
Latitude                           float64
Hospital_Name                       object
Hospital_Type                       object
Hq_Address                          object
Hq_Address1                         object
Hq_Citystring                      float64
Hq_State                            object
Hq_Zip_Code                          int64
County_Name                         object
State_Name                          object
State_Fips                           int64
Cnty_Fips                            int64
Fips                                 int64
Num_Licensed_Beds                  float64
Num_Staffed_Beds                   float64
Num_Icu_Beds                         int64
Adult_Icu_Beds                       int64
Pedi_Icu_Beds                      float64
Bed_Utilization                    float64
Potential_Increase_In_Bed_Capac      int64
Avg_Ventilator_Usage               float64
dtype: object

In [ ]:
Lets view the data by State

In [37]:
dataFrame.groupby('State_Name').first().filter(['Bed_Utilization','Potential_Increase_In_Bed_Capac'])

                      Bed_Utilization  Potential_Increase_In_Bed_Capac
State_Name
Alabama                      0.623113                               30
Alaska                       0.740093                               10
Arizona                      0.468836                                0
Arkansas                     0.188706                                0
California                   0.280393                                0
Colorado                     0.336525                                9
Connecticut                  0.587062                                0
Delaware                     0.687720                                0
District of Columbia         0.918004                                0
Florida                      0.832845                              154
Georgia                      0.199114                               15
Hawaii                       0.723933                                9
Idaho                        0.572088                                0
Illinois                     0.489284                               59
Indiana                      0.610082                                0
Iowa                         0.044274                                0
Kansas                       0.349918                                0
Kentucky                     0.753315                                0
Louisiana                    0.167872                                0
Maine                        0.508920                                0
Maryland                     0.680301                                0
Massachusetts                0.738866                                0
Michigan                     0.248219                                0
Minnesota                    0.375562                                0
Mississippi                  0.296324                                0
Missouri                          NaN                                0
New Mexico                        NaN                                0
New York                          NaN                                0
North Dakota                      NaN                                0
Oregon                            NaN                                0
Pennsylvania                      NaN                                0
Rhode Island                      NaN                                0
South Carolina                    NaN                                0
West Virginia                     NaN                                0

Now, we will connect the SQL Server (Synapse/SQL DB) and load the data

In [51]:
import pyodbc
from sqlalchemy import create_engine

AZUREUID = 'USERNAME'                                    # Azure SQL database userid
AZUREPWD = 'PASSWORD'                                # Azure SQL database password
AZURESRV = 'example.database.windows.net'   # Azure SQL database server name (fully qualified)
AZUREDB = 'DATABASE'                          # Azure SQL database name (if it does not exit, pandas will create it)
TABLE = 'tableName'                                      # Azure SQL database table name
DRIVER = 'ODBC Driver 13 for SQL Server'                 # ODBC Driver

#Create connection string for connecting to SQL Server / Synapse using ODBC
connectionstring = 'mssql+pyodbc://{uid}:{password}@{server}:1433/{database}?driver={driver}'.format(
        uid=AZUREUID,
        password=AZUREPWD,
        server=AZURESRV,
        database=AZUREDB,
        driver=DRIVER.replace(' ', '+'))
#Create engine using the connection string created above
engn = create_engine(connectionstring)

#Write data from data frame into the database. This function will create a table if it does not exist and if it exists it will replace the data.
#Parameters:-
#  name: The name of the table that you want to write the data in. 
#  con: The Db connection
#  schema: Specify the schema (if database flavor supports this). If None, use default schema.
#
#  if_exists:     How to behave if the table already exists.
    #     fail: Raise a ValueError.
    #     replace: Drop the table before inserting new values.
    #     append: Insert new values to the existing table.
#  index: bool, default True - Write DataFrame index as a column. Uses index_label as the column name in the table.
df.to_sql('REPLACE_WITH_TABLE_NAME', con=engn, schema='REPLACE_WITH_SCHEMA', if_exists='append', index=False)

Lets verify if the data has been written to the table.

In [54]:
query = 'SELECT * FROM definitive_HC.stagingdhc'.format(table=TABLE)
engn.begin()
dfsql = pd.read_sql(query, engn)

print(dfsql.head())

   Row_ID   Load_Date     Load_Time  Longitude  Latitude  \
0      11  2020-07-16  08:38:11.861    -92.329    38.937
1      35  2020-07-16  08:38:11.861    -86.941    31.431
2      23  2020-07-16  08:38:11.861    -86.495    33.933
3       1  2020-07-16  08:38:11.861   -112.066    33.495
4      19  2020-07-16  08:38:11.861    -87.888    30.519

                                       Hospital_Name  \
0          Harry S Truman Memorial Veterans Hospital
1                           Evergreen Medical Center
2                                 St Vincents Blount
3  Phoenix VA Health Care System (AKA Carl T Hayd...
4                                    Thomas Hospital

                    Hospital_Type              Hq_Address Hq_Address1  \
0                     VA Hospital         800 Hospital Dr        None
1  Short Term Acute Care Hospital       101 Crestview Ave        None
2        Critical Access Hospital        150 Gilbreath Dr        None
3                     VA Hospital  650 E Indian School Rd        None
4  Short Term Acute Care Hospital          750 Morphy Ave        None

  Hq_Citystring    ...      Fips  Num_Licensed_Beds Num_Staffed_Beds  \
0          None    ...     29019               89.0             89.0
1          None    ...      1035               58.0             44.0
2          None    ...      1009               25.0             25.0
3          None    ...      4013               62.0             62.0
4          None    ...      1003              150.0            129.0

  Num_Icu_Beds  Adult_Icu_Beds  Pedi_Icu_Beds  Bed_Utilization  \
0            2               2            NaN              NaN
1            8               8            0.0         0.293836
2            6               6            0.0         0.499069
3            0               0            NaN              NaN
4           17              17            0.0         0.770054

   Potential_Increase_In_Bed_Capac  Avg_Ventilator_Usage  filename
0                                0                   2.0      None
1                               14                   0.0      None
2                                0                   2.0      None
3                                0                   0.0      None
4                               21                   3.0      None

[5 rows x 26 columns]